<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="JAYGANESH-PC" name="testcase.Testcasepractice" tests="1" failures="0" timestamp="18 Sep 2019 16:54:31 GMT" time="0.000" errors="1">
  <testcase name="TC001_Create_An_Account" time="0.000" classname="testcase.Testcasepractice">
    <error type="org.testng.TestNGException" message="
Method public static void testcase.Testcasepractice.TC001_Create_An_Account(java.util.Hashtable) throws java.io.IOException requires a @DataProvider named : data_collection">
      <![CDATA[org.testng.TestNGException: 
Method public static void testcase.Testcasepractice.TC001_Create_An_Account(java.util.Hashtable) throws java.io.IOException requires a @DataProvider named : data_collection
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:273)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1303)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1019)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1108)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- TC001_Create_An_Account -->
</testsuite> <!-- testcase.Testcasepractice -->
